[colors.primary]
background = '#000000'
foreground = '#e6d4d8'

[colors.selection]
text = '#e6d4d8'
background = '#52263e'

[colors.cursor]
text = '#000000'
cursor = '#ac3232'

[colors.normal]
black   = '#0d0d14'
red     = '#e54a42'
green   = '#4cac31'
yellow  = '#d7b62f'
blue    = '#de5142'
magenta = '#4f0000'
cyan    = '#ac3232'
white   = '#b4a5a5'

[colors.bright]
black   = '#827575'
red     = '#e86c6c'
green   = '#7ece67'
yellow  = '#ffe680'
blue    = '#bd4b4b'
magenta = '#df7070'
cyan    = '#f0a3a3'
white   = '#f9f0f0'
