cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #412a33
selection_background  #e1bdc9
url_color             #ffb0cf

color0   #131313
color1   #ff7279
color2   #a0ff7f
color3   #ffe172
color4   #f298bb
color5   #76324d
color6   #ffb0cf
color7   #ffeff5
color8   #a5999e
color9   #ff9fa3
color10  #bcffa5
color11  #ffeca5
color12  #ffbbd6
color13  #ffc7dd
color14  #ffdbe9
color15  #fff8fb
