cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #d14d41
url_color             #d14d41

color0   #100F0F
color1   #f03c3a
color2   #5fd141
color3   #ffda3d
color4   #e44c37
color5   #600800
color6   #D14D41
color7   #dbcac9
color8   #877a79
color9   #ff7c7b
color10  #9bfa81
color11  #ffe784
color12  #e56a5f
color13  #ff8e84
color14  #ffb6af
color15  #fff6f6
