cursor #e6d4d8
cursor_text_color #d1b8c0

foreground            #e6d4d8
background            #000000
selection_foreground  #0d0d14
selection_background  #ac3232
url_color             #ac3232

color0   #0d0d14
color1   #e54a42
color2   #4cac31
color3   #d7b62f
color4   #de5142
color5   #4f0000
color6   #ac3232
color7   #b4a5a5
color8   #827575
color9   #e86c6c
color10  #7ece67
color11  #ffe680
color12  #bd4b4b
color13  #df7070
color14  #f0a3a3
color15  #f9f0f0
