#----------------------#
### --- MONITORS --- ###
#----------------------#
#BenQ
monitorrule=name:^DP-3$,width:2560,height:1440,x:0,y:0,refresh:143.998993
#Samsung
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,x:-1920,y:0,refresh:60
#Cintiq
monitorrule=name:^DP-2$,width:3840,height:2160,x:0,y:1440,refresh:59.997002

