#------------------------#
### --- WORKSPACES --- ###
#------------------------#
# Change your layout here for each workspace.
# tile, scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller
#BENQ
tagrule = id:1, no_hide:1, monitor_name:^DP-3$, layout_name:scroller #Primary
tagrule = id:2, no_hide:1, monitor_name:^DP-3$, layout_name:scroller #Messaging
tagrule = id:3, no_hide:1, monitor_name:^DP-3$, layout_name:scroller #Gaming
tagrule = id:4, no_hide:1, monitor_name:^DP-3$, layout_name:scroller #Games

#SAMSUNG
tagrule = id:5, no_hide:1, monitor_name:^HDMI-A-1$, layout_name:scroller #Secondary

#CINTIQ
tagrule = id:6, monitor_name:^DP-2$, layout_name:center_tile #Cintiq

#tagrule = id:7, layout_name:tile
#tagrule = id:8, layout_name:tile
#tagrule = id:9, layout_name:tile


#-------------------------------#
### --- APPLICATION SETUP --- ###
#-------------------------------#

