# dothelp — quick reference for custom dotfile commands
# File: ~/.config/fish/functions/dothelp.fish

function dothelp
    echo ""
    echo "  ── Dotfile Commands ──────────────────────────────────────"
    echo ""
    echo "  dotback  -all              backup all configs"
    echo "  dotback  -app              backup one app (e.g. dotback -niri)"
    echo "  dotback  -list             show backup and package status"
    echo ""
    echo "  restore  -all              check packages + restore all configs"
    echo "  restore  -app              restore one app (e.g. restore -niri)"
    echo "  restore  -list             show backup and package status"
    echo ""
    echo "  install                    interactive fresh install"
    echo "  install  -all              install all packages"
    echo "  install  -flag             install one category:"
    echo "           -core -browsers -media -creative"
    echo "           -hardware -ai -repos -niri -noctalia"
    echo ""
    echo "  clean-cache                clean pacman/paru caches"
    echo "  dothelp                    show this help"
    echo ""
    echo "  ── Apps ──────────────────────────────────────────────────"
    echo ""
    echo "  niri kitty alacritty fastfetch noctalia"
    echo "  fish starship nvim krita"
    echo ""
end
